#ifndef VTERM_KEYCODES_H
#define VTERM_KEYCODES_H

typedef enum {
    VTERM_KEY_NONE = 0,
    VTERM_KEY_ENTER,
    VTERM_KEY_TAB,
    VTERM_KEY_BACKSPACE,
    VTERM_KEY_ESCAPE,
    VTERM_KEY_UP,
    VTERM_KEY_DOWN,
    VTERM_KEY_LEFT,
    VTERM_KEY_RIGHT,
    VTERM_KEY_HOME,
    VTERM_KEY_END,
    VTERM_KEY_INSERT,
    VTERM_KEY_DELETE,
    VTERM_KEY_PAGEUP,
    VTERM_KEY_PAGEDOWN,
    VTERM_KEY_F1,
    VTERM_KEY_F2,
    VTERM_KEY_F3,
    VTERM_KEY_F4,
    VTERM_KEY_F5,
    VTERM_KEY_F6,
    VTERM_KEY_F7,
    VTERM_KEY_F8,
    VTERM_KEY_F9,
    VTERM_KEY_F10,
    VTERM_KEY_F11,
    VTERM_KEY_F12
} VTermKey;

#endif // VTERM_KEYCODES_H
